version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./frontend:/home/node/app:cached
      - frontend_node_modules:/home/node/app/node_modules
    ports:
      - 8080:8080
  server:
    build:
      context: ./server
      dockerfile: ./docker/golang/Dockerfile
    command: ["make", "debug"]
    volumes:
      - ./server:/go/app:cached
    ports:
      - 9090:9090

volumes:
  frontend_node_modules:
